# Generated by Django 3.0.5 on 2020-04-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200430_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
