# Generated by Django 3.0.5 on 2020-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
