# Generated by Django 3.0.5 on 2020-04-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_messagemodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='group',
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='time')),
                ('body', models.TextField(verbose_name='body')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_group', to='core.Group', verbose_name='group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'group message',
                'verbose_name_plural': 'group messags',
                'ordering': ('-time',),
            },
        ),
    ]
